<?php

use App\Http\Controllers\App\AuxiliaryAppController;
use App\Http\Controllers\App\BudgetController;
use App\Http\Controllers\App\CashSessionController;
use App\Http\Controllers\App\ChecklistController;
use App\Http\Controllers\App\CompanyController;
use App\Http\Controllers\App\CustomerController;
use App\Http\Controllers\App\CustomerEquipmentController;
use App\Http\Controllers\App\DashboardController;
use App\Http\Controllers\App\EquipmentController;
use App\Http\Controllers\App\AccountPayableController;
use App\Http\Controllers\App\ExpenseController;
use App\Http\Controllers\App\FiscalDocumentController;
use App\Http\Controllers\App\FiscalEmissionController;
use App\Http\Controllers\App\FiscalSettingController;
use App\Http\Controllers\App\FollowUpController;
use App\Http\Controllers\App\HelpTopicController;
use App\Http\Controllers\App\TechnicianCommissionController;
use App\Http\Controllers\App\MaintenanceContractController;
use App\Http\Controllers\App\ImageController;
use App\Http\Controllers\App\IntelIndicatorController;
use App\Http\Controllers\App\LabelPrintingController;
use App\Http\Controllers\App\MessageController;
use App\Http\Controllers\App\OrderController;
use App\Http\Controllers\App\OtherController;
use App\Http\Controllers\App\PaymentFeeSettingController;
use App\Http\Controllers\App\PartController;
use App\Http\Controllers\App\PartImportController;
use App\Http\Controllers\App\ProfileController;
use App\Http\Controllers\App\PurchaseOrderController;
use App\Http\Controllers\App\QualityIndicatorController;
use App\Http\Controllers\App\ReceiptController;
use App\Http\Controllers\App\ReportController;
use App\Http\Controllers\App\SaleController;
use App\Http\Controllers\App\ScheduleController;
use App\Http\Controllers\App\ServiceController;
use App\Http\Controllers\App\SupplierController;
use App\Http\Controllers\App\TenantImprovementRequestController;
use App\Http\Controllers\App\UserController;
use App\Http\Controllers\App\WhatsappConnectionController;
use App\Http\Controllers\App\WhatsappMessageController;
use Illuminate\Support\Facades\Route;

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/chartEquipments/{timerange}', [DashboardController::class, 'chartEquipments'])->name('chartEquipments');
Route::get('/fluxsOrders/{timerange}', [DashboardController::class, 'fluxsOrders'])->name('fluxsOrders');
Route::get('/budgetsStatusChart/{timerange}', [DashboardController::class, 'budgetsStatusChart'])->name('budgetsStatusChart');
Route::get('/metricsSystem/{timerange}', [DashboardController::class, 'metricsSystem'])->name('metricsSystem');
Route::get('/kpisFinancialOrder/{timerange}', [DashboardController::class, 'kpisFinancialOrder'])->name('kpisFinancialOrder');
Route::get('/financialRevenueChart/{timerange}', [DashboardController::class, 'financialRevenueChart'])->name('financialRevenueChart');
Route::get('/kpisSchedules/{timerange}', [DashboardController::class, 'kpisSchedules'])->name('kpisSchedules');
Route::get('/schedulesStatusChart/{timerange}', [DashboardController::class, 'schedulesStatusChart'])->name('schedulesStatusChart');
Route::get('/kpisFinancialSales/{timerange}', [DashboardController::class, 'kpisFinancialSales'])->name('kpisFinancialSales');
Route::get('/financialSalesRevenueChart/{timerange}', [DashboardController::class, 'financialSalesRevenueChart'])->name('financialSalesRevenueChart');
Route::get('/kpisPurchases/{timerange}', [DashboardController::class, 'kpisPurchases'])->name('kpisPurchases');
Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
Route::get('/quality-indicators', [QualityIndicatorController::class, 'index'])->name('quality.index');
Route::get('/quality-indicators/metrics/{timerange}', [QualityIndicatorController::class, 'metrics'])->name('quality.metrics');
Route::post('/quality-indicators/{order}/feedback-recovery', [QualityIndicatorController::class, 'updateFeedbackRecovery'])->name('quality.feedback-recovery');
Route::get('/follow-ups', [FollowUpController::class, 'index'])->name('follow-ups.index');
Route::get('/follow-ups/tasks', [FollowUpController::class, 'tasks'])->name('follow-ups.tasks');
Route::get('/follow-ups/performance', [FollowUpController::class, 'performance'])->name('follow-ups.performance');
Route::get('/improvement-requests', [TenantImprovementRequestController::class, 'index'])->name('improvement-requests.index');
Route::post('/improvement-requests', [TenantImprovementRequestController::class, 'store'])->name('improvement-requests.store');
Route::post('/improvement-requests/feedback', [TenantImprovementRequestController::class, 'storeFeedback'])->name('improvement-requests.feedback.store');
Route::post('/follow-ups/{order}/pause', [FollowUpController::class, 'pause'])->name('follow-ups.pause');
Route::post('/follow-ups/{order}/resume', [FollowUpController::class, 'resume'])->name('follow-ups.resume');
Route::post('/follow-ups/{order}/respond', [FollowUpController::class, 'respond'])->name('follow-ups.respond');
Route::post('/follow-ups/{order}/complete-task', [FollowUpController::class, 'completeTask'])->name('follow-ups.complete-task');
Route::post('/follow-ups/{order}/snooze-task', [FollowUpController::class, 'snoozeTask'])->name('follow-ups.snooze-task');
Route::post('/follow-ups/{order}/assign-task', [FollowUpController::class, 'assignTask'])->name('follow-ups.assign-task');
Route::post('/follow-ups/assign-selected', [FollowUpController::class, 'assignSelectedTasks'])->name('follow-ups.assign-selected');

Route::get('customers-duplicate-check', [CustomerController::class, 'duplicateCheck'])->name('customers.duplicate-check');
Route::get('customers/search', [CustomerController::class, 'search'])->name('customers.search');
Route::resource('customers', CustomerController::class);
Route::post('customers/import-customer', [CustomerController::class, 'ImportCustomer'])->name('import.customer');
Route::post('customers/{customer}/equipments', [CustomerEquipmentController::class, 'store'])->name('customers.equipments.store');
Route::post('customers/{customer}/whatsapp', [CustomerController::class, 'sendWhatsapp'])->name('customers.whatsapp.send');
Route::get('customer-equipments/search', [CustomerEquipmentController::class, 'search'])->name('customer-equipments.search');
Route::patch('customer-equipments/{customerEquipment}', [CustomerEquipmentController::class, 'update'])->name('customer-equipments.update');
Route::delete('customer-equipments/{customerEquipment}', [CustomerEquipmentController::class, 'destroy'])->name('customer-equipments.destroy');
Route::resource('messages', MessageController::class);
Route::patch('messages/{message}/read', [MessageController::class, 'read'])->name('messages.read');
Route::patch('orders/{order}/feedback', [OrderController::class, 'markFeedback'])->name('orders.feedback');
Route::resource('orders', OrderController::class);
Route::post('orders/{order}/payments', [OrderController::class, 'storePayment'])->name('orders.payments.store');
Route::post('orders/{order}/payments/mobile-confirm', [OrderController::class, 'confirmMobilePayment'])->name('orders.payments.mobile-confirm');
Route::post('orders/{order}/payments/reminder', [OrderController::class, 'sendPaymentReminder'])->name('orders.payments.reminder');
Route::post('orders/{order}/budget-follow-up', [OrderController::class, 'sendBudgetFollowUp'])->name('orders.budget-follow-up');
Route::post('orders/{order}/customer-update', [OrderController::class, 'sendCustomerUpdate'])->name('orders.customer-update');
Route::delete('orders/{order}/payments/{payment}', [OrderController::class, 'destroyPayment'])->name('orders.payments.destroy');
Route::get('orders/{order}/payments-data', [OrderController::class, 'paymentsData'])->name('orders.payments.data');
Route::post('orders/{order}/fiscal', [OrderController::class, 'registerFiscal'])->name('orders.fiscal.register');
Route::post('orders/{order}/fiscal/emit', [FiscalEmissionController::class, 'emitOrder'])->name('orders.fiscal.emit');
Route::post('orders/{order}/whatsapp', [OrderController::class, 'sendWhatsapp'])->name('orders.whatsapp.send');
Route::post('schedules/{schedule}/local-payment-cashier', [ScheduleController::class, 'registerLocalPaymentCashier'])->name('schedules.local-payment-cashier');
Route::patch('schedules/{schedule}/service-closure-price', [ScheduleController::class, 'defineServiceClosurePrice'])->name('schedules.service-closure-price');
Route::post('schedules/{schedule}/whatsapp', [ScheduleController::class, 'sendWhatsapp'])->name('schedules.whatsapp.send');
Route::resource('schedules', ScheduleController::class);
Route::resource('services', ServiceController::class);
Route::resource('users', UserController::class);
Route::resource('budgets', BudgetController::class);
Route::get('fiscal-documents', [FiscalDocumentController::class, 'index'])->name('fiscal-documents.index');
Route::post('fiscal-documents/{fiscalDocument}/refresh', [FiscalEmissionController::class, 'refresh'])->name('fiscal-documents.refresh');
Route::post('fiscal-documents/{fiscalDocument}/cancel', [FiscalEmissionController::class, 'cancel'])->name('fiscal-documents.cancel');
Route::get('fiscal-documents/{fiscalDocument}/file/{format}', [FiscalEmissionController::class, 'file'])->name('fiscal-documents.file');
Route::get('fiscal-settings', [FiscalSettingController::class, 'show'])->name('fiscal-settings.show');
Route::put('fiscal-settings', [FiscalSettingController::class, 'update'])->name('fiscal-settings.update');
Route::post('fiscal-settings/certificate', [FiscalSettingController::class, 'certificate'])->name('fiscal-settings.certificate');
Route::get('register-equipments/search', [EquipmentController::class, 'search'])->name('register-equipments.search');
Route::resource('register-equipments', EquipmentController::class)->parameters(['register-equipments' => 'equipment']);
Route::resource('register-services', ServiceController::class)->parameters(['register-services' => 'service']);
Route::resource('register-checklists', ChecklistController::class)->parameters(['register-checklists' => 'checklist']);
Route::get('images', [ImageController::class, 'index'])->name('images.index');
Route::post('images', [ImageController::class, 'store'])->name('images.store');
Route::delete('images/{image}', [ImageController::class, 'destroy'])->name('images.destroy');

Route::get('other-settings', [OtherController::class, 'index'])->name('other-settings.index');
Route::put('other-settings/{other}', [OtherController::class, 'update'])->name('other-settings.update');
Route::post('other-settings/{other}/test-mail', [OtherController::class, 'sendTestMail'])->name('other-settings.test-mail');
Route::put('payment-fee-settings', [PaymentFeeSettingController::class, 'update'])->name('payment-fee-settings.update');
Route::get('auxiliary-apps', [AuxiliaryAppController::class, 'index'])->name('auxiliary-apps.index');

Route::resource('company', CompanyController::class);
Route::resource('whatsapp-message', WhatsappMessageController::class)->parameters(['whatsapp-message' => 'whatsappmessage']);
Route::get('whatsapp-connection/status', [WhatsappConnectionController::class, 'status'])->name('whatsapp-connection.status');
Route::get('whatsapp-connection/qr', [WhatsappConnectionController::class, 'qrCode'])->name('whatsapp-connection.qr');
Route::post('whatsapp-connection/connect', [WhatsappConnectionController::class, 'connect'])->name('whatsapp-connection.connect');
Route::post('whatsapp-connection/disconnect', [WhatsappConnectionController::class, 'disconnect'])->name('whatsapp-connection.disconnect');
Route::resource('receipts', ReceiptController::class);

Route::get('receipts/{or}/{tp}', [ReceiptController::class, 'printing'])->name('receipts.printing');
Route::get('receipts/{or}/{tp}/data', [ReceiptController::class, 'printingData'])->name('receipts.printing.data');

Route::resource('label-printing', LabelPrintingController::class);
Route::get('label-printing-print', [LabelPrintingController::class, 'print'])->name('label-printing.print');
Route::put('label-printing-settings', [LabelPrintingController::class, 'updateSettings'])->name('label-printing.settings');
Route::get('/intel/indicators', IntelIndicatorController::class)->middleware('throttle:60,1')->name('intel.indicators');
Route::get('/parts/search', [PartController::class, 'search'])->name('parts.search');
Route::get('/parts/import/template', [PartImportController::class, 'template'])->name('parts.import.template');
Route::post('/parts/import/preview', [PartImportController::class, 'preview'])->middleware('throttle:30,1')->name('parts.import.preview');
Route::post('/parts/import', [PartImportController::class, 'store'])->middleware('throttle:10,1')->name('parts.import.store');
Route::resource('/parts', PartController::class);
Route::get('/parts/{part}/print-label', [PartController::class, 'printLabel'])->name('parts.print-label');
Route::post('/orders/remove-part', [OrderController::class, 'removePart'])->name('orders.removePart');

Route::resource('suppliers', SupplierController::class)->except(['show', 'create', 'edit']);

Route::resource('purchase-orders', PurchaseOrderController::class)->except(['show']);
Route::post('purchase-orders/{purchase_order}/send', [PurchaseOrderController::class, 'send'])->name('purchase-orders.send');
Route::post('purchase-orders/{purchase_order}/receive', [PurchaseOrderController::class, 'receive'])->name('purchase-orders.receive');
Route::post('purchase-orders/{purchase_order}/cancel', [PurchaseOrderController::class, 'cancel'])->name('purchase-orders.cancel');
Route::resource('/sales', SaleController::class);
Route::post('/sales/{sale}/cancel', [SaleController::class, 'cancel'])->name('sales.cancel');
Route::post('/sales/{sale}/fiscal', [SaleController::class, 'registerFiscal'])->name('sales.fiscal.register');
Route::post('/sales/{sale}/fiscal/emit', [FiscalEmissionController::class, 'emitSale'])->name('sales.fiscal.emit');
Route::resource('/expenses', ExpenseController::class)->except(['show', 'create', 'edit']);
Route::resource('accounts-payable', AccountPayableController::class)->except(['show', 'create', 'edit']);
Route::post('accounts-payable/{accounts_payable}/register-payment', [AccountPayableController::class, 'registerPayment'])->name('accounts-payable.register-payment');
Route::get('/technician-commissions', [TechnicianCommissionController::class, 'index'])->name('technician-commissions.index');
Route::resource('maintenance-contracts', MaintenanceContractController::class)->except(['show', 'create', 'edit']);
Route::get('maintenance-contracts/{maintenance_contract}/print', [MaintenanceContractController::class, 'printing'])->name('maintenance-contracts.printing');
Route::post('maintenance-contracts/{maintenance_contract}/renew', [MaintenanceContractController::class, 'renew'])->name('maintenance-contracts.renew');
Route::post('maintenance-contracts/{maintenance_contract}/suspend', [MaintenanceContractController::class, 'suspend'])->name('maintenance-contracts.suspend');
Route::post('maintenance-contracts/{maintenance_contract}/reactivate', [MaintenanceContractController::class, 'reactivate'])->name('maintenance-contracts.reactivate');
Route::post('maintenance-contracts/{maintenance_contract}/cancel', [MaintenanceContractController::class, 'cancel'])->name('maintenance-contracts.cancel');
Route::get('/cashier', [CashSessionController::class, 'index'])->name('cashier.index');
Route::post('/cashier/open', [CashSessionController::class, 'open'])->name('cashier.open');
Route::post('/cashier/{cashSession}/withdrawal', [CashSessionController::class, 'withdrawal'])->name('cashier.withdrawal');
Route::post('/cashier/{cashSession}/withdrawal/{movement}/cancel', [CashSessionController::class, 'cancelWithdrawal'])->name('cashier.withdrawal.cancel');
Route::post('/cashier/{cashSession}/close', [CashSessionController::class, 'close'])->name('cashier.close');
Route::resource('/reports', ReportController::class);

Route::get('/ajuda', [HelpTopicController::class, 'index'])->name('help-topics.index');
Route::get('/ajuda/{slug}', [HelpTopicController::class, 'show'])->name('help-topics.show');
